version: '{build}'

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  appveyor_boost_version: 1.65.0
  appveyor_python_exe: C:\Python36-x64\python.exe

configuration:
  - MinSizeRel

platform:
  - x64

matrix:
  fast_finish: true

install:
  - choco install make

build_script:
  - echo Simple CMake projects
  - make simple
  - make static
  - make dynamic

  - echo Boost 1.58.0
  - make boost/58

  - echo Boost 1.72.0
  - make boost/72

  - echo Boost 1.65.0
  - make boost/65
