language: cpp
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - cmake
      - g++-multilib
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

jobs:
  include:
    - name: Run clang-format
      language: shell
      addons:
        apt:
          update: true
          packages:
            - clang-format-9
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      script: ./tools/clang-format.py --clang-format clang-format-9

    - name: Simple CMake projects
      script:
        - make simple
        - make static
        - make dynamic

    - name: Boost 1.58
      script: make boost/58

    - name: Boost 1.72
      script: make boost/72

    - name: Boost 1.65
      script: make boost/65
      env:
        travis_boost_version: 1.65.0
        configuration: MinSizeRel
        platform: x64
