language: cpp
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - cmake
      - g++-multilib
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

jobs:
  include:
    - name: Simple CMake projects
      script:
        - >-
          ./cmake/build/build.py
          --install "$HOME/install/simple"
          --configuration Release
          -- cmake/examples/simple
        - "$HOME/install/simple/bin/foo"
        - ./.ci/verify_arch.sh "$HOME/install/simple/bin/foo" x64

        - >-
          ./cmake/build/build.py
          --install "$HOME/install/static"
          --configuration Debug
          -- cmake/examples/static
          -D "CMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/cmake/toolchains/gcc-x86.cmake"
        - "$HOME/install/static/bin/foo"
        - ./.ci/verify_arch.sh "$HOME/install/static/bin/foo" x86

        - >-
          ./cmake/build/build.py
          --install "$HOME/install/dynamic"
          --configuration Release
          -- cmake/examples/dynamic
        - LD_LIBRARY_PATH="$HOME/install/dynamic/lib" "$HOME/install/dynamic/bin/foo"
        - ./.ci/verify_arch.sh "$HOME/install/dynamic/bin/foo" x64

    - name: Boost 1.58
      script:
        - ./boost/build/build.py download 1.58.0
        - >-
          ./boost/build/build.py build
          --configuration Debug
          --platform x86
          -- ./boost_1_58_0
          --with-filesystem --with-program_options
        - bash -o pipefail -c 'find boost_1_58_0/stage -type f | sort'
        - >-
          ./cmake/build/build.py
          --install "$HOME/install/boost_1_58_0"
          --configuration Debug
          -- cmake/examples/boost
          -D "BOOST_ROOT=$TRAVIS_BUILD_DIR/boost_1_58_0"
          -D "BOOST_LIBRARYDIR=$TRAVIS_BUILD_DIR/boost_1_58_0/stage/x86/Debug/lib"
          -D "CMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/cmake/toolchains/gcc-x86.cmake"
        - "$HOME/install/boost_1_58_0/bin/foo"
        - ./.ci/verify_arch.sh "$HOME/install/boost_1_58_0/bin/foo" x86

    - name: Boost 1.72
      script:
        - ./boost/build/build.py download --cache . 1.72.0
        - >-
          ./boost/build/build.py build
          --configuration Debug Release
          --platform x86 x64
          --link shared
          -- ./boost_1_72_0
          --with-filesystem --with-program_options
        - bash -o pipefail -c 'find boost_1_72_0/stage -type f | sort'
        - >-
          ./cmake/build/build.py
          --install "$HOME/install/boost_1_72_0"
          --configuration Release
          -- cmake/examples/boost
          -D "BOOST_ROOT=$TRAVIS_BUILD_DIR/boost_1_72_0"
          -D "BOOST_LIBRARYDIR=$TRAVIS_BUILD_DIR/boost_1_72_0/stage/x64/Release/lib"
          -D Boost_USE_STATIC_LIBS=OFF
        - >-
          LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/boost_1_72_0/stage/x64/Release/lib"
          "$HOME/install/boost_1_72_0/bin/foo"
        - ./.ci/verify_arch.sh "$HOME/install/boost_1_72_0/bin/foo" x64

    - name: Boost 1.65
      script:
        - ./boost/build/ci/travis.py --link static -- --with-filesystem --with-program_options
        - bash -o pipefail -c 'find "$HOME/boost_1_65_0/stage" -type f | sort'
      env:
        travis_boost_version: 1.65.0
        configuration: Release
        platform: x64
