language: cpp
os: linux
dist: focal

branches:
  only:
    - travis

addons:
  apt:
    packages:
      - g++-multilib

jobs:
  include:
    - name: Run clang-format
      language: minimal
      addons:
        apt:
          packages:
            - clang-format-9
      script: ./tools/clang-format.py --clang-format clang-format-9

    - name: Simple CMake projects
      script:
        - make -f .ci/Makefile simple
        - make -f .ci/Makefile static
        - make -f .ci/Makefile dynamic

    - name: Boost 1.58
      script: make -f .ci/Makefile boost/58

    - name: Boost 1.72
      script: make -f .ci/Makefile boost/72

    - name: Boost 1.65
      script: make -f .ci/Makefile boost/65
      env:
        boost_version: 1.65.0
        configuration: MinSizeRel
        platform: x64
