name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  schedule:
    # Weekly, at 01:30 AM on Friday (somewhat randomly chosen).
    - cron: '30 01 * * 5'
  workflow_dispatch:

jobs:
  lint:
    name: Linting
    uses: ./.github/workflows/lint.yml

  basic:
    name: Basic usage
    uses: ./.github/workflows/basic.yml

  boost_download:
    name: Boost (download)
    uses: ./.github/workflows/boost_download.yml

  boost_toolsets:
    name: Boost (toolsets)
    uses: ./.github/workflows/boost_toolsets.yml

  example_toolsets:
    name: Examples (toolsets)
    uses: ./.github/workflows/example_toolsets.yml

  msvc_versions:
    name: Visual Studio versions
    uses: ./.github/workflows/msvc_versions.yml

  # Build a Python package and upload to PyPI.
  publish:
    name: Publish
    needs:
      - lint
      - basic
      - boost_toolsets
      - example_toolsets
    uses: ./.github/workflows/publish.yml
