name: CI (GitHub)

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 5:30 AM on Saturday (somewhat randomly chosen).
    - cron: '30 5 * * 6'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolset: [gcc, clang, msvc]
        configuration: [Debug, Release]
        exclude:
          - {os: ubuntu-latest, toolset: msvc}
          - {os: windows-latest, toolset: gcc}
          - {os: windows-latest, toolset: clang}
    runs-on: '${{ matrix.os }}'
    name: '${{ matrix.os }} / ${{ matrix.toolset }} / ${{ matrix.configuration }}'
    defaults:
      run:
        shell: pwsh
    env:
      TOOLSET: '${{ matrix.toolset }}'
      PLATFORM: x64
      CONFIGURATION: '${{ matrix.configuration }}'
      BOOST_VERSION: 1.72.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Cache Boost
        uses: actions/cache@v2
        with:
          path: '${{ runner.workspace }}/build/boost_*.tar.gz'
          key: 'boost_${{ env.BOOST_VERSION }}'
      - name: Build Boost
        run: python -m project.ci.boost -- --with-filesystem
      - name: Build example project
        run: python -m project.ci.cmake --install --subdir examples/boost
      - name: Run example project
        run: ./.ci/run_foo.ps1 (Join-Path $env:GITHUB_WORKSPACE .. build install bin foo)
