# This workflow pretends like it's being run on Travis by setting the
# appropriate environment variables.

name: CI (Travis)

on:
  push:
    paths:
      - 'examples/**'
      - 'project/**'
  pull_request:
  schedule:
    # Weekly, at 5:30 AM on Saturday (somewhat randomly chosen).
    - cron: '30 5 * * 6'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    name: '${{ matrix.configuration }}'
    defaults:
      run:
        shell: pwsh
    env:
      # https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
      TRAVIS: 'true'
      TRAVIS_BUILD_DIR: '${{ github.workspace }}/examples/boost'
      PLATFORM: x64
      CONFIGURATION: '${{ matrix.configuration }}'
      BOOST_VERSION: 1.81.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Cache Boost
        uses: actions/cache@v3
        with:
          path: '${{ github.workspace }}/examples/build/boost_*.tar.gz'
          key: 'boost_${{ env.BOOST_VERSION }}'
      - name: Build Boost
        run: python -m project.ci.boost --hint Travis -- --with-filesystem
      - name: Build example project
        run: python -m project.ci.cmake --hint Travis --install
      - name: Run example project
        run: ./.ci/run_foo.ps1 (Join-Path $env:TRAVIS_BUILD_DIR .. build install bin foo)
